# test_name: "Benchmark" # the series of tests being run in thesis
# test_name: "ModTests1" # the series of tests being run in thesis
# test_name: "FinalTests" # the series of tests being run in thesis
test_name: devel

n: 1
# start_n:1 
set_n: 4
random_seed: 10000

n_train_steps: 50000
# n_test_laps: 2
n_test_laps: 100

n_obstacles: 8
racing: True
# racing: False

map_name: "columbia_small"
# map_name: "f1_aut"

runs:
  # - architecture: "E2e"
  # - architecture: "Serial"
  - architecture: "Mod"



