# test_name: "Benchmark" # the series of tests being run in thesis
# test_name: "FastTests" # the series of tests being run in thesis
# test_name: "SlowTests" # the series of tests being run in thesis
# test_name: "BigRacelineTests" # the series of tests being run in thesis
test_name: "devel"

# architecture: "E2e"
# architecture: "Serial"
# architecture: "Mod"
# architecture: "PP"
# architecture: "FTG"

n: 1
set_n: 3
random_seed: 2000

n_train_steps: 50000
# n_test_laps: 2
n_test_laps: 100

n_obstacles: 8
# racing: True
racing: False

map_name: "columbia_small"
# map_name: "f1_aut"
# map_name: "f1_gbr"

runs:
  # - map_name: "f1_aut"
  # - map_name: "f1_mco"
  # - map_name: "f1_esp"
  # - map_name: "f1_gbr"
  # - map_name: "columbia_small"

  - architecture: "E2e"
  # - architecture: "Serial"
  # - architecture: "Mod"



