# test_name: "Benchmark" # the series of tests being run in thesis
# test_name: "FastTests" # the series of tests being run in thesis
test_name: "SlowTests" # the series of tests being run in thesis

# architecture: "E2e"
# architecture: "Serial"
# architecture: "Mod"
# architecture: "PP"


n: 1
set_n: 1
random_seed: 1000

# n_train_steps: 50000
# n_test_laps: 2
n_test_laps: 100

n_obstacles: 6
# racing: True
racing: False

map_name: "columbia_small"
# map_name: "f1_aut"

runs:
  # - map_name: "f1_aut"
  # - map_name: "f1_mco"
  # - map_name: "f1_esp"
  # - map_name: "f1_gbr"
  # - map_name: "columbia_small"

  - architecture: "E2e"
  - architecture: "Serial"
  - architecture: "Mod"



