test_name: "Benchmark" # the series of tests being run in thesis

# planner: "PP"  # the kind of planner
# planner: "FGM"
# planner: "Agent"

architecture: "E2e"
# architecture: "Serial"
# architecture: "Mod"


n: 1
set_n: 2

n_train_steps: 5000
n_test_laps: 2
# n_test_laps: 10


racing: False


runs:
  # - map_name: "f1_aut"
  # - map_name: "f1_mco"
  # - map_name: "f1_esp"
  # - map_name: "f1_gbr"
  - map_name: "columbia_small"



