

# Vehicle params
max_v: 7
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2
mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158
vehicle_speed: 2          # speed at which the vehilce is set to travel at

# agent parameters
n_beams: 60               # number of beams used by agent
n_scans: 2
range_finder_scale: 10     # scaling of beams for NN
h_size: 100               # size of hidden layers in NN
# r1: 0.012                 # heading & velocity reward value
# r2: 0.006                 # distance reward penalty
# rk: 0.04                  # constant reward applied at every step

r_k_scan: 0.08
r_velocity: 1
r_distance: 0.5


#simulator
sim_steps: 10              # Number of simulator steps per planning step
max_steps: 5000
# add a simtime step?
# random_seed: 2000          # Seed for NumPy randomness
# random_seed: 1000          # Seed for NumPy randomness

# PurePursuit planner values
lookahead: 1.4
v_gain: 0.9
v_min_plan: 1            # minimum speed for selecting a steering angle to prevent instability


#save_paths
vehicle_path: "Data/Vehicles/"
max_laptime: 180


